package com.example.zunay.patientdetails;

import android.app.Activity;
import android.os.Bundle;
import android.os.Environment;
import android.view.View;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.Toast;

import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.util.HSSFColor;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;

import static java.lang.Math.sqrt;

public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        String s= null;
        try{
            Save(s);
        }catch (IOException e){e.printStackTrace();}
    }
    public void Save(String s) throws IOException {
        File Root = Environment.getExternalStorageDirectory();
        File Dir = new File(Root.getAbsolutePath() + "/PatientDetails");
        if (!Dir.exists()) {
            Dir.mkdir();
            File file = new File(Root.getAbsolutePath() + "/PatientDetails","PatientDetails.xls");

            //New Workbook
            Workbook wb = new HSSFWorkbook();
            Cell c;
            //Cell style for header row
            CellStyle cs = wb.createCellStyle();
            cs.setFillForegroundColor(HSSFColor.LIME.index);
            cs.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
            //New Sheet
            Sheet sheet1;
            sheet1 = wb.createSheet("patient");
            // Generate column headings
            Row row = sheet1.createRow(0);
            int i = 0;
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails1));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails2));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails3));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails4));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails5));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails6));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails7));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails8));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails9));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails10));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails11));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails12));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails13));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails14));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails15));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails16));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails17));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails18));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails19));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails20));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails21));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails22));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails23));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails24));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails25));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails26));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails27));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails28));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails29));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails30));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails31));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails32));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails33));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails34));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails35));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails36));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails37));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails38));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails39));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails40));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails41));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails42));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails43));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails44));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails45));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails46));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails47));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails48));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails49));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails50));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails51));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails52));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails53));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails54));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails55));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails56));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails57));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails58));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails59));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails60));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails61));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails62));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails63));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails64));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails65));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails66));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails67));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails68));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails69));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails70));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails71));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails72));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails73));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails74));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails75));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails76));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails77));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails78));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails78e));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails79));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails80));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails81));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails82));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails83));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails84));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails85));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails86));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails87));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails88));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails89));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails90));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails91));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails92));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails93));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails94));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails95));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails96));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails97));c.setCellStyle(cs);
            c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails98));c.setCellStyle(cs);
            c = row.createCell(i);c.setCellValue(getString(R.string.patientdetails99));c.setCellStyle(cs);
            for (int itr = 0; itr < 100; itr++) {
                sheet1.setColumnWidth(itr,(15*500));
            }
            //c = row.createCell(i);c.setCellValue(getString(R.string.patientdetails98));c.setCellStyle(cs);
            FileOutputStream fileOutputStream = new FileOutputStream(file,false);
            wb.write(fileOutputStream);
            Toast.makeText(getApplicationContext(),"Saved",Toast.LENGTH_SHORT).show();
        }
        else {
            File file = new File(Root.getAbsolutePath() + "/PatientDetails","PatientDetails.xls");
            if(!file.exists()) {
                Workbook wb = new HSSFWorkbook();
                Cell c;
                CellStyle cs = wb.createCellStyle();
                cs.setFillForegroundColor(HSSFColor.LIME.index);
                cs.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
                Sheet sheet1;
                sheet1 = wb.createSheet("patient");
                Row row = sheet1.createRow(0);
                int i = 0;
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails1));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails2));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails3));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails4));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails5));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails6));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails7));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails8));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails9));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails10));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails11));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails12));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails13));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails14));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails15));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails16));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails17));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails18));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails19));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails20));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails21));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails22));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails23));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails24));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails25));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails26));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails27));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails28));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails29));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails30));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails31));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails32));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails33));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails34));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails35));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails36));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails37));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails38));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails39));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails40));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails41));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails42));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails43));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails44));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails45));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails46));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails47));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails48));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails49));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails50));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails51));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails52));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails53));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails54));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails55));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails56));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails57));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails58));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails59));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails60));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails61));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails62));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails63));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails64));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails65));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails66));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails67));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails68));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails69));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails70));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails71));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails72));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails73));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails74));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails75));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails76));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails77));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails78));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails78e));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails79));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails80));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails81));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails82));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails83));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails84));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails85));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails86));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails87));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails88));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails89));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails90));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails91));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails92));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails93));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails94));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails95));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails96));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails97));c.setCellStyle(cs);
                c = row.createCell(i);i++;c.setCellValue(getString(R.string.patientdetails98));c.setCellStyle(cs);
                c = row.createCell(i);c.setCellValue(getString(R.string.patientdetails99));c.setCellStyle(cs);

                for (int itr = 0; itr < 100; itr++) {
                    sheet1.setColumnWidth(itr, (15 * 500));
                }

                FileOutputStream fileOutputStream = new FileOutputStream(file, false);
                wb.write(fileOutputStream);
                Toast.makeText(getApplicationContext(), "Saved", Toast.LENGTH_SHORT).show();
            }

        }

    }
    public void Update(View view) throws IOException {
        HSSFWorkbook workbook;

        try {
            Spinner spinner3=(Spinner)findViewById(R.id.spinner3);
            Spinner spinner8=(Spinner)findViewById(R.id.spinner8);
            Spinner spinner35=(Spinner)findViewById(R.id.spinner35);
            Spinner spinner36=(Spinner)findViewById(R.id.spinner36);
            Spinner spinner37=(Spinner)findViewById(R.id.spinner37);
            Spinner spinner78e=(Spinner)findViewById(R.id.spinner78e);
            Spinner spinner71=(Spinner)findViewById(R.id.spinner71);
            Spinner spinner13=(Spinner)findViewById(R.id.spinner13);
            Spinner spinner14=(Spinner)findViewById(R.id.spinner14);
            Spinner spinner15=(Spinner)findViewById(R.id.spinner15);
            Spinner spinner16=(Spinner)findViewById(R.id.spinner16);
            Spinner spinner17=(Spinner)findViewById(R.id.spinner17);
            Spinner spinner18=(Spinner)findViewById(R.id.spinner18);
            Spinner spinner19=(Spinner)findViewById(R.id.spinner19);
            Spinner spinner20=(Spinner)findViewById(R.id.spinner20);
            Spinner spinner21=(Spinner)findViewById(R.id.spinner21);
            Spinner spinner22=(Spinner)findViewById(R.id.spinner22);
            Spinner spinner23=(Spinner)findViewById(R.id.spinner23);
            Spinner spinner24=(Spinner)findViewById(R.id.spinner24);



            EditText msg1= (EditText)findViewById(R.id.editText1);
            EditText msg2= (EditText)findViewById(R.id.editText2);
            String msg3 = spinner3.getSelectedItem().toString();
            EditText msg4= (EditText)findViewById(R.id.editText4);
            EditText msg5= (EditText)findViewById(R.id.editText5);
            EditText msg6= (EditText)findViewById(R.id.editText6);
            EditText msg7= (EditText)findViewById(R.id.editText7);
            String msg8 = spinner8.getSelectedItem().toString();
            EditText msg9a= (EditText)findViewById(R.id.editText9a);
            EditText msg9b= (EditText)findViewById(R.id.editText9b);
            EditText msg10= (EditText)findViewById(R.id.editText10);
            EditText msg11= (EditText)findViewById(R.id.editText11);
            EditText msg12= (EditText)findViewById(R.id.editText12);
            String msg13 = spinner13.getSelectedItem().toString();
            String msg14 = spinner14.getSelectedItem().toString();
            String msg15 = spinner15.getSelectedItem().toString();
            String msg16 = spinner16.getSelectedItem().toString();
            String msg17= spinner17.getSelectedItem().toString();
            String msg18 = spinner18.getSelectedItem().toString();
            String msg19 = spinner19.getSelectedItem().toString();
            String msg20 = spinner20.getSelectedItem().toString();
            String msg21 = spinner21.getSelectedItem().toString();
            String msg22 = spinner22.getSelectedItem().toString();
            String msg23 = spinner23.getSelectedItem().toString();
            String msg24 = spinner24.getSelectedItem().toString();
            EditText msg25= (EditText)findViewById(R.id.editText25);
            EditText msg26= (EditText)findViewById(R.id.editText26);
            EditText msg27= (EditText)findViewById(R.id.editText27);
            EditText msg28= (EditText)findViewById(R.id.editText28);
            EditText msg29= (EditText)findViewById(R.id.editText29);
            EditText msg30= (EditText)findViewById(R.id.editText30);
            EditText msg31= (EditText)findViewById(R.id.editText31);
            EditText msg32= (EditText)findViewById(R.id.editText32);
            EditText msg33= (EditText)findViewById(R.id.editText33);
            EditText msg34= (EditText)findViewById(R.id.editText34);
            String msg35 = spinner35.getSelectedItem().toString();
            String msg36 = spinner36.getSelectedItem().toString();
            String msg37 = spinner37.getSelectedItem().toString();
            EditText msg38= (EditText)findViewById(R.id.editText38);
            EditText msg39= (EditText)findViewById(R.id.editText39);
            EditText msg40= (EditText)findViewById(R.id.editText40);
            EditText msg41= (EditText)findViewById(R.id.editText41);
            EditText msg42= (EditText)findViewById(R.id.editText42);
            EditText msg43= (EditText)findViewById(R.id.editText43);
            EditText msg44= (EditText)findViewById(R.id.editText44);
            EditText msg45= (EditText)findViewById(R.id.editText45);
            EditText msg46= (EditText)findViewById(R.id.editText46);
            EditText msg47= (EditText)findViewById(R.id.editText47);
            EditText msg48= (EditText)findViewById(R.id.editText48);
            EditText msg49= (EditText)findViewById(R.id.editText49);
            EditText msg50= (EditText)findViewById(R.id.editText50);
            EditText msg51= (EditText)findViewById(R.id.editText51);
            EditText msg52= (EditText)findViewById(R.id.editText52);
            EditText msg53= (EditText)findViewById(R.id.editText53);
            EditText msg54= (EditText)findViewById(R.id.editText54);
            EditText msg55= (EditText)findViewById(R.id.editText55);
            EditText msg56= (EditText)findViewById(R.id.editText56);
            EditText msg57= (EditText)findViewById(R.id.editText57);
            EditText msg58= (EditText)findViewById(R.id.editText58);
            EditText msg59= (EditText)findViewById(R.id.editText59);
            EditText msg60= (EditText)findViewById(R.id.editText60);
            EditText msg61= (EditText)findViewById(R.id.editText61);
            EditText msg62= (EditText)findViewById(R.id.editText62);
            EditText msg63= (EditText)findViewById(R.id.editText63);
            EditText msg64= (EditText)findViewById(R.id.editText64);
            EditText msg65= (EditText)findViewById(R.id.editText65);
            EditText msg66= (EditText)findViewById(R.id.editText66);
            EditText msg67= (EditText)findViewById(R.id.editText67);
            EditText msg68= (EditText)findViewById(R.id.editText68);
            EditText msg69= (EditText)findViewById(R.id.editText69);
            EditText msg70= (EditText)findViewById(R.id.editText70);
            String msg71 = spinner71.getSelectedItem().toString();
            EditText msg72= (EditText)findViewById(R.id.editText72);
            EditText msg73= (EditText)findViewById(R.id.editText73);
            EditText msg74= (EditText)findViewById(R.id.editText74);
            EditText msg75= (EditText)findViewById(R.id.editText75);
            EditText msg76= (EditText)findViewById(R.id.editText76);
            EditText msg77= (EditText)findViewById(R.id.editText77);
            EditText msg78= (EditText)findViewById(R.id.editText78);
            String msg78e = spinner78e.getSelectedItem().toString();
            EditText msg79= (EditText)findViewById(R.id.editText79);
            EditText msg80= (EditText)findViewById(R.id.editText80);
            EditText msg81= (EditText)findViewById(R.id.editText81);
            EditText msg82= (EditText)findViewById(R.id.editText82);
            EditText msg83= (EditText)findViewById(R.id.editText83);
            EditText msg84= (EditText)findViewById(R.id.editText84);
            EditText msg85= (EditText)findViewById(R.id.editText85);
            EditText msg86= (EditText)findViewById(R.id.editText86);
            EditText msg87= (EditText)findViewById(R.id.editText87);
            EditText msg88= (EditText)findViewById(R.id.editText88);
            EditText msg89= (EditText)findViewById(R.id.editText89);
            EditText msg90= (EditText)findViewById(R.id.editText90);
            EditText msg91= (EditText)findViewById(R.id.editText91);
            EditText msg92= (EditText)findViewById(R.id.editText92);
            EditText msg93= (EditText)findViewById(R.id.editText93);
            EditText msg94= (EditText)findViewById(R.id.editText94);
            EditText msg95= (EditText)findViewById(R.id.editText95);
            EditText msg96= (EditText)findViewById(R.id.editText96);
            EditText msg97= (EditText)findViewById(R.id.editText97);
            EditText msg98= (EditText)findViewById(R.id.editText98);
            EditText msg99= (EditText)findViewById(R.id.editText99);

            String message9= new String("0");
            String message9a= msg9a.getText().toString().trim();
            String message9b= msg9b.getText().toString().trim();
            double sum=0.0;

            if(message9a!=null || !message9a.equals("") && message9b!=null || !message9b.equals(""))
            {
                double wt=Double.valueOf(msg9a.getText().toString());
                double ht=Double.valueOf(msg9b.getText().toString());
                sum=sqrt((wt*ht)/3600);
                message9= String.valueOf(sum);
            }
            else if(message9a=="0" && message9b=="0")
            {
                message9= String.valueOf(sum);
            }

            File Root = Environment.getExternalStorageDirectory();
            FileInputStream file = new FileInputStream(new File(Root.getAbsolutePath() + "/PatientDetails","PatientDetails.xls"));
            workbook = new HSSFWorkbook(file);
            int rowCount = workbook.getSheetAt(0).getLastRowNum();
            Row row = workbook.getSheetAt(0).createRow(++rowCount);
            Cell c = null;
            int i = 0;
            c = row.createCell(i);i++;c.setCellValue(msg1.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg2.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg3);
            c = row.createCell(i);i++;c.setCellValue(msg4.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg5.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg6.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg7.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg8);
            c = row.createCell(i);i++;c.setCellValue(message9);
            c = row.createCell(i);i++;c.setCellValue(msg10.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg11.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg12.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg13);
            c = row.createCell(i);i++;c.setCellValue(msg14);
            c = row.createCell(i);i++;c.setCellValue(msg15);
            c = row.createCell(i);i++;c.setCellValue(msg16);
            c = row.createCell(i);i++;c.setCellValue(msg17);
            c = row.createCell(i);i++;c.setCellValue(msg18);
            c = row.createCell(i);i++;c.setCellValue(msg19);
            c = row.createCell(i);i++;c.setCellValue(msg20);
            c = row.createCell(i);i++;c.setCellValue(msg21);
            c = row.createCell(i);i++;c.setCellValue(msg22);
            c = row.createCell(i);i++;c.setCellValue(msg23);
            c = row.createCell(i);i++;c.setCellValue(msg24);
            c = row.createCell(i);i++;c.setCellValue(msg25.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg26.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg27.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg28.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg29.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg30.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg31.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg32.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg33.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg34.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg35);
            c = row.createCell(i);i++;c.setCellValue(msg36);
            c = row.createCell(i);i++;c.setCellValue(msg37);
            c = row.createCell(i);i++;c.setCellValue(msg38.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg39.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg40.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg41.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg42.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg43.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg44.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg45.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg46.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg47.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg48.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg49.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg50.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg51.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg52.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg53.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg54.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg55.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg56.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg57.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg58.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg59.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg60.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg61.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg62.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg63.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg64.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg65.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg66.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg67.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg68.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg69.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg70.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg71);
            c = row.createCell(i);i++;c.setCellValue(msg72.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg73.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg74.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg75.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg76.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg77.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg78.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg78e);
            c = row.createCell(i);i++;c.setCellValue(msg79.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg80.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg81.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg82.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg83.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg84.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg85.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg86.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg87.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg88.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg89.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg90.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg91.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg92.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg93.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg94.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg95.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg96.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg97.getText().toString());
            c = row.createCell(i);i++;c.setCellValue(msg98.getText().toString());
            c = row.createCell(i);c.setCellValue(msg99.getText().toString());


            Toast.makeText(getApplicationContext(),"SAVED"+rowCount,Toast.LENGTH_SHORT).show();

            file.close();

            FileOutputStream outFile =new FileOutputStream(new File(Root.getAbsolutePath() + "/PatientDetails","PatientDetails.xls"));
            workbook.write(outFile);
            if (null != outFile)
                outFile.close();
            //outFile.close();
            clearData();


        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void clearData() {
        EditText msg1= (EditText)findViewById(R.id.editText1);
        EditText msg2= (EditText)findViewById(R.id.editText2);
        EditText msg4= (EditText)findViewById(R.id.editText4);
        EditText msg5= (EditText)findViewById(R.id.editText5);
        EditText msg6= (EditText)findViewById(R.id.editText6);
        EditText msg7= (EditText)findViewById(R.id.editText7);
        EditText msg9a= (EditText)findViewById(R.id.editText9a);
        EditText msg9b= (EditText)findViewById(R.id.editText9b);
        EditText msg10= (EditText)findViewById(R.id.editText10);
        EditText msg11= (EditText)findViewById(R.id.editText11);
        EditText msg12= (EditText)findViewById(R.id.editText12);
        EditText msg25= (EditText)findViewById(R.id.editText25);
        EditText msg26= (EditText)findViewById(R.id.editText26);
        EditText msg27= (EditText)findViewById(R.id.editText27);
        EditText msg28= (EditText)findViewById(R.id.editText28);
        EditText msg29= (EditText)findViewById(R.id.editText29);
        EditText msg30= (EditText)findViewById(R.id.editText30);
        EditText msg31= (EditText)findViewById(R.id.editText31);
        EditText msg32= (EditText)findViewById(R.id.editText32);
        EditText msg33= (EditText)findViewById(R.id.editText33);
        EditText msg34= (EditText)findViewById(R.id.editText34);
        EditText msg38= (EditText)findViewById(R.id.editText38);
        EditText msg39= (EditText)findViewById(R.id.editText39);
        EditText msg40= (EditText)findViewById(R.id.editText40);
        EditText msg41= (EditText)findViewById(R.id.editText41);
        EditText msg42= (EditText)findViewById(R.id.editText42);
        EditText msg43= (EditText)findViewById(R.id.editText43);
        EditText msg44= (EditText)findViewById(R.id.editText44);
        EditText msg45= (EditText)findViewById(R.id.editText45);
        EditText msg46= (EditText)findViewById(R.id.editText46);
        EditText msg47= (EditText)findViewById(R.id.editText47);
        EditText msg48= (EditText)findViewById(R.id.editText48);
        EditText msg49= (EditText)findViewById(R.id.editText49);
        EditText msg50= (EditText)findViewById(R.id.editText50);
        EditText msg51= (EditText)findViewById(R.id.editText51);
        EditText msg52= (EditText)findViewById(R.id.editText52);
        EditText msg53= (EditText)findViewById(R.id.editText53);
        EditText msg54= (EditText)findViewById(R.id.editText54);
        EditText msg55= (EditText)findViewById(R.id.editText55);
        EditText msg56= (EditText)findViewById(R.id.editText56);
        EditText msg57= (EditText)findViewById(R.id.editText57);
        EditText msg58= (EditText)findViewById(R.id.editText58);
        EditText msg59= (EditText)findViewById(R.id.editText59);
        EditText msg60= (EditText)findViewById(R.id.editText60);
        EditText msg61= (EditText)findViewById(R.id.editText61);
        EditText msg62= (EditText)findViewById(R.id.editText62);
        EditText msg63= (EditText)findViewById(R.id.editText63);
        EditText msg64= (EditText)findViewById(R.id.editText64);
        EditText msg65= (EditText)findViewById(R.id.editText65);
        EditText msg66= (EditText)findViewById(R.id.editText66);
        EditText msg67= (EditText)findViewById(R.id.editText67);
        EditText msg68= (EditText)findViewById(R.id.editText68);
        EditText msg69= (EditText)findViewById(R.id.editText69);
        EditText msg70= (EditText)findViewById(R.id.editText70);
        EditText msg72= (EditText)findViewById(R.id.editText72);
        EditText msg73= (EditText)findViewById(R.id.editText73);
        EditText msg74= (EditText)findViewById(R.id.editText74);
        EditText msg75= (EditText)findViewById(R.id.editText75);
        EditText msg76= (EditText)findViewById(R.id.editText76);
        EditText msg77= (EditText)findViewById(R.id.editText77);
        EditText msg78= (EditText)findViewById(R.id.editText78);
        EditText msg79= (EditText)findViewById(R.id.editText79);
        EditText msg80= (EditText)findViewById(R.id.editText80);
        EditText msg81= (EditText)findViewById(R.id.editText81);
        EditText msg82= (EditText)findViewById(R.id.editText82);
        EditText msg83= (EditText)findViewById(R.id.editText83);
        EditText msg84= (EditText)findViewById(R.id.editText84);
        EditText msg85= (EditText)findViewById(R.id.editText85);
        EditText msg86= (EditText)findViewById(R.id.editText86);
        EditText msg87= (EditText)findViewById(R.id.editText87);
        EditText msg88= (EditText)findViewById(R.id.editText88);
        EditText msg89= (EditText)findViewById(R.id.editText89);
        EditText msg90= (EditText)findViewById(R.id.editText90);
        EditText msg91= (EditText)findViewById(R.id.editText91);
        EditText msg92= (EditText)findViewById(R.id.editText92);
        EditText msg93= (EditText)findViewById(R.id.editText93);
        EditText msg94= (EditText)findViewById(R.id.editText94);
        EditText msg95= (EditText)findViewById(R.id.editText95);
        EditText msg96= (EditText)findViewById(R.id.editText96);
        EditText msg97= (EditText)findViewById(R.id.editText97);
        EditText msg98= (EditText)findViewById(R.id.editText98);
        EditText msg99= (EditText)findViewById(R.id.editText99);
        msg1.setText("");
        msg2.setText("");
        msg4.setText("");
        msg5.setText("");
        msg6.setText("");
        msg7.setText("");
        msg9a.setText("0");
        msg9b.setText("0");
        msg10.setText("");
        msg11.setText("");
        msg12.setText("");
        msg25.setText("");
        msg26.setText("");
        msg27.setText("");
        msg28.setText("");
        msg29.setText("");
        msg30.setText("");
        msg31.setText("");
        msg32.setText("");
        msg33.setText("");
        msg34.setText("");
        msg38.setText("");
        msg39.setText("");
        msg40.setText("");
        msg40.setText("");
        msg41.setText("");
        msg42.setText("");
        msg43.setText("");
        msg44.setText("");
        msg45.setText("");
        msg46.setText("");
        msg47.setText("");
        msg48.setText("");
        msg49.setText("");
        msg50.setText("");
        msg51.setText("");
        msg52.setText("");
        msg53.setText("");
        msg54.setText("");
        msg55.setText("");
        msg56.setText("");
        msg57.setText("");
        msg58.setText("");
        msg59.setText("");
        msg60.setText("");
        msg61.setText("");
        msg62.setText("");
        msg63.setText("");
        msg64.setText("");
        msg65.setText("");
        msg66.setText("");
        msg67.setText("");
        msg68.setText("");
        msg69.setText("");
        msg70.setText("");
        msg72.setText("");
        msg73.setText("");
        msg74.setText("");
        msg75.setText("");
        msg76.setText("");
        msg77.setText("");
        msg78.setText("");
        msg79.setText("");
        msg80.setText("");
        msg81.setText("");
        msg82.setText("");
        msg83.setText("");
        msg84.setText("");
        msg85.setText("");
        msg86.setText("");
        msg87.setText("");
        msg88.setText("");
        msg89.setText("");
        msg90.setText("");
        msg91.setText("");
        msg92.setText("");
        msg93.setText("");
        msg94.setText("");
        msg95.setText("");
        msg96.setText("");
        msg97.setText("");
        msg98.setText("");
        msg99.setText("");



    }
}
